// <auto-generated />
using System;
using Amphoreus.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amphoreus.Persistence.Migrations
{
    [DbContext(typeof(AmphoreusDBContext))]
    partial class AmphoreusDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Amphoreus.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "iceCoffe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "hotCoffe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "blendedCoffe"
                        });
                });

            modelBuilder.Entity("Amphoreus.Domain.Coffe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CoffeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("cateogoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoffeId");

                    b.HasIndex("cateogoryId");

                    b.ToTable("coffes");
                });

            modelBuilder.Entity("Amphoreus.Domain.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ingredients");
                });

            modelBuilder.Entity("Amphoreus.Domain.coffeIngredient", b =>
                {
                    b.Property<Guid>("coffeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ingredientId")
                        .HasColumnType("TEXT");

                    b.HasKey("coffeId", "ingredientId");

                    b.HasIndex("ingredientId");

                    b.ToTable("coffeIngredient");
                });

            modelBuilder.Entity("Amphoreus.Domain.Coffe", b =>
                {
                    b.HasOne("Amphoreus.Domain.Coffe", null)
                        .WithMany("coffes")
                        .HasForeignKey("CoffeId");

                    b.HasOne("Amphoreus.Domain.Category", "Category")
                        .WithMany("Coffes")
                        .HasForeignKey("cateogoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Amphoreus.Domain.coffeIngredient", b =>
                {
                    b.HasOne("Amphoreus.Domain.Coffe", "Coffe")
                        .WithMany("coffeIngredients")
                        .HasForeignKey("coffeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amphoreus.Domain.Ingredient", "Ingredient")
                        .WithMany("coffeIngredients")
                        .HasForeignKey("ingredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coffe");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Amphoreus.Domain.Category", b =>
                {
                    b.Navigation("Coffes");
                });

            modelBuilder.Entity("Amphoreus.Domain.Coffe", b =>
                {
                    b.Navigation("coffeIngredients");

                    b.Navigation("coffes");
                });

            modelBuilder.Entity("Amphoreus.Domain.Ingredient", b =>
                {
                    b.Navigation("coffeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
